<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251206020153 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE delivery (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(255) DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, relance_count INT NOT NULL, last_reminder_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, partner_id INT DEFAULT NULL, document_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3781EC109393F8FE ON delivery (partner_id)');
        $this->addSql('CREATE INDEX IDX_3781EC10C33F7837 ON delivery (document_id)');
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) DEFAULT NULL, filepath VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, title VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE partner (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE delivery ADD CONSTRAINT FK_3781EC109393F8FE FOREIGN KEY (partner_id) REFERENCES partner (id)');
        $this->addSql('ALTER TABLE delivery ADD CONSTRAINT FK_3781EC10C33F7837 FOREIGN KEY (document_id) REFERENCES document (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE delivery DROP CONSTRAINT FK_3781EC109393F8FE');
        $this->addSql('ALTER TABLE delivery DROP CONSTRAINT FK_3781EC10C33F7837');
        $this->addSql('DROP TABLE delivery');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE partner');
    }
}
